import EducationScheduleView from '@/components/EducationScheduleView'
import { supabaseRestGetSafe } from '@/lib/supabaseRest'
import type { EducationScheduleRow } from '@/lib/adminTypes'

/**
 * Supabase 장애·키 미설정 시에도 페이지가 비지 않도록 유지하는 폴백 데이터.
 * 평상시 실제 일정은 관리자 대시보드(/admin/schedules)에서 관리합니다.
 */
const FALLBACK_SCHEDULES: EducationScheduleRow[] = [
  {
    id: 'fallback-1',
    year: 2026,
    month: 3,
    period: '3월28일',
    course_name: '인지발달심리상담지도사 아동발달평가사 (질환별 사례교육)',
    education_name: '장애 아동의 시지각 문제에 대한 이해와 중재',
    education_time: '14:00-18:00',
    instructor: '최강미, 안소현',
    schedule_note: null,
    detailed_time: null,
    location: null,
    director: '조선영',
    method: '실시간온라인',
    target: '작업치료사 70명',
    category: '인지발달심리상담지도사',
    sort_order: 1,
    is_visible: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'fallback-2',
    year: 2026,
    month: 4,
    period: '4월19일',
    course_name: '인지발달심리상담지도사 아동발달평가사 (질환별 사례교육)',
    education_name: '질환별 장애아동의 이해와 중재 : 자폐스펙트럼장애 아동의 행동 중재와 사회기술훈련',
    education_time: '10:00-17:10',
    instructor: '유애리, ABA',
    schedule_note: '4/19',
    detailed_time: null,
    location: '서울창업허브 공덕 본관 9층 세미나실',
    director: '조선영',
    method: '오프라인',
    target: '임상가, 학생, 40명',
    category: '인지발달심리상담지도사',
    sort_order: 2,
    is_visible: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'fallback-3',
    year: 2026,
    month: 5,
    period: '5월30일',
    course_name: '인지발달심리상담지도사 아동발달평가사 (질환별 사례교육)',
    education_name: '사례로 이해하는 조산 & 뇌성마비 아동 작업치료',
    education_time: '09:00-16:00',
    instructor: '김영호, 윤인진',
    schedule_note: '5/30',
    detailed_time: null,
    location: '줌온라인',
    director: '박윤이',
    method: '온라인실시간',
    target: '임상가, 학생',
    category: '인지발달심리상담지도사',
    sort_order: 3,
    is_visible: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'fallback-4',
    year: 2026,
    month: 6,
    period: '6월말',
    course_name: '인지발달심리상담지도사 아동발달평가사 (부모교육)',
    education_name: 'OPC 교육 - 사례공유',
    education_time: '3시간(추후 시간 연장논의)',
    instructor: '주유미, 유은영, 임상가1',
    schedule_note: null,
    detailed_time: null,
    location: null,
    director: '조선영',
    method: '온라인실시간',
    target: '임상가',
    category: '인지발달심리상담지도사',
    sort_order: 4,
    is_visible: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'fallback-5',
    year: 2026,
    month: 8,
    period: '8월 말',
    course_name: '아동발달평가사',
    education_name: '임상에서 바로쓰는 영유아 발달평가 (베일리-3 발달위험군 아동(36개월)평가사례)',
    education_time: '16시간 (2일)',
    instructor: '박윤이, 김영란, 유영미, 함형광',
    schedule_note: null,
    detailed_time: null,
    location: null,
    director: '박윤이',
    method: '온라인실시간 또는 오프라인',
    target: '임상가',
    category: '아동발달평가사',
    sort_order: 5,
    is_visible: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'fallback-6',
    year: 2026,
    month: 9,
    period: '9월말',
    course_name: '아동발달평가사 1급 자격 교육',
    education_name: '아동발달평가서 작성',
    education_time: '3시간',
    instructor: '최강미, 함형광',
    schedule_note: null,
    detailed_time: null,
    location: null,
    director: '박윤이',
    method: '온라인실시간',
    target: '2급 대상자',
    category: '아동발달평가사',
    sort_order: 6,
    is_visible: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'fallback-7',
    year: 2026,
    month: 11,
    period: '11월 중순',
    course_name: '인지발달상담지도사 자격교육과정',
    education_name: '2급자격과정',
    education_time: '16시간',
    instructor: null,
    schedule_note: null,
    detailed_time: null,
    location: null,
    director: '조선영',
    method: '온라인 녹화',
    target: '임상가, 학생',
    category: '인지발달심리상담지도사',
    sort_order: 7,
    is_visible: true,
    created_at: '',
    updated_at: '',
  },
]

export default async function EducationSchedulePage() {
  const rows = await supabaseRestGetSafe<EducationScheduleRow[]>(
    '/rest/v1/education_schedules?select=*&is_visible=eq.true&order=month.asc,sort_order.asc',
    [],
  )
  const schedules = rows.length > 0 ? rows : FALLBACK_SCHEDULES

  return <EducationScheduleView schedules={schedules} />
}
